[project]
name = "openbb-app"
version = "0.2.1
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Roger Ye", email = "shugaoye@yahoo.com" }
]
requires-python = ">=3.11"
dependencies = [
    "mysharelib>=1.0.4",
    "openbb>=4.7.0",
    "openbb-akshare>=1.0.5",
    "openbb-tushare>=1.0.0",
    "uvicorn>=0.40.0",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[project.scripts]
openbb-app = "openbb_app.main:start"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
